/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FacilitaRouteImport } from './routes/facilita'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EmpreendimentoIdRouteImport } from './routes/empreendimento.$id'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminPerfilRouteImport } from './routes/admin.perfil'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminDepoimentosRouteImport } from './routes/admin.depoimentos'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitaRoute = FacilitaRouteImport.update({
  id: '/facilita',
  path: '/facilita',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EmpreendimentoIdRoute = EmpreendimentoIdRouteImport.update({
  id: '/empreendimento/$id',
  path: '/empreendimento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerfilRoute = AdminPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepoimentosRoute = AdminDepoimentosRouteImport.update({
  id: '/depoimentos',
  path: '/depoimentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contato': typeof ContatoRoute
  '/facilita': typeof FacilitaRoute
  '/login': typeof LoginRoute
  '/sobre': typeof SobreRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/depoimentos': typeof AdminDepoimentosRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/empreendimento/$id': typeof EmpreendimentoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/facilita': typeof FacilitaRoute
  '/login': typeof LoginRoute
  '/sobre': typeof SobreRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/depoimentos': typeof AdminDepoimentosRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/empreendimento/$id': typeof EmpreendimentoIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contato': typeof ContatoRoute
  '/facilita': typeof FacilitaRoute
  '/login': typeof LoginRoute
  '/sobre': typeof SobreRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/depoimentos': typeof AdminDepoimentosRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/perfil': typeof AdminPerfilRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/empreendimento/$id': typeof EmpreendimentoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contato'
    | '/facilita'
    | '/login'
    | '/sobre'
    | '/admin/blog'
    | '/admin/depoimentos'
    | '/admin/leads'
    | '/admin/perfil'
    | '/admin/projects'
    | '/admin/usuarios'
    | '/empreendimento/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/facilita'
    | '/login'
    | '/sobre'
    | '/admin/blog'
    | '/admin/depoimentos'
    | '/admin/leads'
    | '/admin/perfil'
    | '/admin/projects'
    | '/admin/usuarios'
    | '/empreendimento/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contato'
    | '/facilita'
    | '/login'
    | '/sobre'
    | '/admin/blog'
    | '/admin/depoimentos'
    | '/admin/leads'
    | '/admin/perfil'
    | '/admin/projects'
    | '/admin/usuarios'
    | '/empreendimento/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  FacilitaRoute: typeof FacilitaRoute
  LoginRoute: typeof LoginRoute
  SobreRoute: typeof SobreRoute
  EmpreendimentoIdRoute: typeof EmpreendimentoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilita': {
      id: '/facilita'
      path: '/facilita'
      fullPath: '/facilita'
      preLoaderRoute: typeof FacilitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/empreendimento/$id': {
      id: '/empreendimento/$id'
      path: '/empreendimento/$id'
      fullPath: '/empreendimento/$id'
      preLoaderRoute: typeof EmpreendimentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perfil': {
      id: '/admin/perfil'
      path: '/perfil'
      fullPath: '/admin/perfil'
      preLoaderRoute: typeof AdminPerfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/depoimentos': {
      id: '/admin/depoimentos'
      path: '/depoimentos'
      fullPath: '/admin/depoimentos'
      preLoaderRoute: typeof AdminDepoimentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminDepoimentosRoute: typeof AdminDepoimentosRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminPerfilRoute: typeof AdminPerfilRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminDepoimentosRoute: AdminDepoimentosRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminPerfilRoute: AdminPerfilRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContatoRoute: ContatoRoute,
  FacilitaRoute: FacilitaRoute,
  LoginRoute: LoginRoute,
  SobreRoute: SobreRoute,
  EmpreendimentoIdRoute: EmpreendimentoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
